"""v3.39.7 baseline schema

Revision ID: 489afd0e62f9
Revises:
Create Date: 2026-06-18 20:59:05.653302

================================================================================
GATE #4 BASELINE — MANUAL POST-AUTOGENERATE FIXUPS (re-apply if regenerated!)
================================================================================
Produced by `alembic revision --autogenerate` against an empty SQLite DB, then
hand-adjusted. Autogenerate will NOT reproduce these on a regen — re-apply every
time this file is regenerated:

  #1  Boolean server_defaults → sa.false() / sa.true() (NOT sa.text('0'/'1')).
      Autogenerate renders boolean defaults as integer literals, which break
      CREATE TABLE on Postgres ("column is of type boolean but default is
      integer"). sa.false()/sa.true() render 0/1 on SQLite, false/true on PG.
      Affected: commander_bracket_rules.{allows_*,competitive},
      game_changer_cards.active, game_seats.art_background_hidden.
      (Integer max_game_changers and float weight correctly stay sa.text(...).)

DELIBERATE / DOCUMENTED DELTAS from the frozen prod schema (intentional, not bugs):
  - Native `boolean` for game_changer_cards.active + all ORM bools (NOT integer).
  - scryfall_cards.full_art stays Integer (cache reads `= 1`); prices Text; cmc Float.
  - decks UNIQUE(user_id, name) replaces prod's legacy global UNIQUE(name).
  - Timestamps are NAIVE `TIMESTAMP` (sa.DateTime) on purpose — matches the naive-UTC
    data and v3.36.13's single-flip-point. Do NOT add timezone=True here.
  - ORM-contract FKs added that prod's drifted tables lacked — 0 orphans, safe.

RECOVERED prod raw-SQL invariants the ORM had omitted (encoded in models.py, each
`# gate-#5 pending verification`): FK ondelete on password_reset_tokens +
token_inventory + watchlist + deck_token_requirements.token_inventory_id, and 3
PARTIAL unique indexes (uq_playgroups_join_code, uq_watchlist_user_card_id/_name).
AMENDMENT 2026-06-18 (rehearsal): trade_items.showcase_item_id → SET NULL added
(was NO ACTION, blocked the orphan sweep's showcase_items CASCADE delete).
================================================================================
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "489afd0e62f9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scryfall_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("set_code", sa.String(length=32), nullable=False),
        sa.Column("set_name", sa.String(length=255), nullable=True),
        sa.Column("collector_number", sa.String(length=32), nullable=False),
        sa.Column("rarity", sa.String(length=64), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("type_line", sa.Text(), nullable=True),
        sa.Column("oracle_text", sa.Text(), nullable=True),
        sa.Column("price_usd", sa.String(length=32), nullable=True),
        sa.Column("price_usd_foil", sa.String(length=32), nullable=True),
        sa.Column("price_usd_etched", sa.String(length=32), nullable=True),
        sa.Column("colors", sa.String(length=64), nullable=True),
        sa.Column("color_identity", sa.String(length=64), nullable=True),
        sa.Column("mana_cost", sa.String(length=128), nullable=True),
        sa.Column("cmc", sa.Float(), nullable=True),
        sa.Column("legalities", sa.Text(), nullable=True),
        sa.Column("full_art", sa.Boolean(), nullable=True),
        sa.Column("frame_effects", sa.Text(), nullable=True),
        sa.Column("set_type", sa.String(length=64), nullable=True),
        sa.Column("layout", sa.String(length=64), nullable=True),
        sa.Column("loyalty", sa.String(length=16), nullable=True),
        sa.Column("defense", sa.String(length=16), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cards_collector_number"), ["collector_number"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_cards_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_cards_scryfall_id"), ["scryfall_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_cards_set_code"), ["set_code"], unique=False)

    op.create_table(
        "commander_bracket_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bracket", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("max_game_changers", sa.Integer(), server_default=sa.text("0"), nullable=False),
        # MANUAL FIXUP #1 (see header) — portable boolean defaults, not sa.text('0').
        sa.Column(
            "allows_mass_land_denial", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "allows_extra_turn_chains", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "allows_two_card_combos", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column(
            "allows_combo_as_primary", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column("competitive", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("rules_version", sa.String(length=32), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bracket", "rules_version"),
        sqlite_autoincrement=True,
    )
    op.create_table(
        "scryfall_bulk_meta",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "scryfall_cards",
        sa.Column("scryfall_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("set_code", sa.Text(), nullable=True),
        sa.Column("set_name", sa.Text(), nullable=True),
        sa.Column("collector_number", sa.Text(), nullable=True),
        sa.Column("rarity", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("type_line", sa.Text(), nullable=True),
        sa.Column("oracle_text", sa.Text(), nullable=True),
        sa.Column("price_usd", sa.Text(), nullable=True),
        sa.Column("price_usd_foil", sa.Text(), nullable=True),
        sa.Column("price_usd_etched", sa.Text(), nullable=True),
        sa.Column("colors", sa.Text(), nullable=True),
        sa.Column("color_identity", sa.Text(), nullable=True),
        sa.Column("mana_cost", sa.Text(), nullable=True),
        sa.Column("cmc", sa.Float(), nullable=True),
        sa.Column("legalities", sa.Text(), nullable=True),
        sa.Column("full_art", sa.Integer(), nullable=True),
        sa.Column("frame_effects", sa.Text(), nullable=True),
        sa.Column("set_type", sa.Text(), nullable=True),
        sa.Column("layout", sa.Text(), nullable=True),
        sa.Column("produced_tokens", sa.Text(), nullable=True),
        sa.Column("loyalty", sa.Text(), nullable=True),
        sa.Column("defense", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("scryfall_id"),
    )
    with op.batch_alter_table("scryfall_cards", schema=None) as batch_op:
        batch_op.create_index("ix_scryfall_cards_name", ["name"], unique=False)
        batch_op.create_index(
            "ix_scryfall_cards_set_collector", ["set_code", "collector_number"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("deck_view_mode", sa.String(length=16), nullable=False),
        sa.Column("deck_group_by", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_signed_in_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "card_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=False),
        sa.Column(
            "confidence", sa.String(length=16), server_default=sa.text("'medium'"), nullable=False
        ),
        sa.Column(
            "source",
            sa.String(length=32),
            server_default=sa.text("'oracle_text_rule'"),
            nullable=False,
        ),
        sa.Column(
            "last_reviewed",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("card_id", "tag"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("card_tags", schema=None) as batch_op:
        batch_op.create_index("ix_card_tags_card", ["card_id"], unique=False)
        batch_op.create_index("ix_card_tags_tag", ["tag"], unique=False)

    op.create_table(
        "game_changer_cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("card_name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("date_added", sa.Date(), nullable=True),
        sa.Column("date_removed", sa.Date(), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.true(), nullable=False),  # FIXUP #1
        sa.Column("rules_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("card_name", "rules_version"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("game_changer_cards", schema=None) as batch_op:
        batch_op.create_index("ix_game_changer_active", ["active"], unique=False)

    op.create_table(
        "import_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_batches_user_id"), ["user_id"], unique=False)

    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "playgroups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("join_code", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("playgroups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_playgroups_created_by"), ["created_by"], unique=False)
        batch_op.create_index(batch_op.f("ix_playgroups_name"), ["name"], unique=False)
        batch_op.create_index(
            "uq_playgroups_join_code",
            ["join_code"],
            unique=True,
            sqlite_where=sa.text("join_code IS NOT NULL"),
            postgresql_where=sa.text("join_code IS NOT NULL"),
        )

    op.create_table(
        "showcases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("showcases", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_showcases_user_id"), ["user_id"], unique=False)

    op.create_table(
        "storage_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["storage_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("storage_locations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_storage_locations_mode"), ["mode"], unique=False)
        batch_op.create_index(batch_op.f("ix_storage_locations_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_storage_locations_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_storage_locations_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_storage_locations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "variant_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_variant_groups_user_name"),
    )
    with op.batch_alter_table("variant_groups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_variant_groups_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_variant_groups_user_id"), ["user_id"], unique=False)

    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("card_name", sa.Text(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlist_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "uq_watchlist_user_card_id",
            ["user_id", "card_id"],
            unique=True,
            sqlite_where=sa.text("card_id IS NOT NULL"),
            postgresql_where=sa.text("card_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_watchlist_user_card_name",
            ["user_id", "card_name"],
            unique=True,
            sqlite_where=sa.text("card_name IS NOT NULL"),
            postgresql_where=sa.text("card_name IS NOT NULL"),
        )

    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("storage_location_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("format", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("intent_pod", sa.String(length=16), nullable=True),
        sa.Column("intent_speed", sa.String(length=16), nullable=True),
        sa.Column("intent_combo", sa.String(length=16), nullable=True),
        sa.Column("intent_winning", sa.String(length=16), nullable=True),
        sa.Column("intent_played", sa.String(length=16), nullable=True),
        sa.Column("blurb", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("variant_group_id", sa.Integer(), nullable=True),
        sa.Column("is_brew", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["variant_group_id"], ["variant_groups.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_decks_user_name"),
    )
    with op.batch_alter_table("decks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decks_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_decks_storage_location_id"), ["storage_location_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_decks_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_decks_variant_group_id"), ["variant_group_id"], unique=False
        )

    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("played_at", sa.DateTime(), nullable=False),
        sa.Column("format", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("turn_count", sa.Integer(), nullable=True),
        sa.Column("first_seat_number", sa.Integer(), nullable=True),
        sa.Column("client_token", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("playgroup_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["playgroup_id"], ["playgroups.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_games_playgroup_id"), ["playgroup_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_games_user_id"), ["user_id"], unique=False)

    op.create_table(
        "inventory_rows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("storage_location_id", sa.Integer(), nullable=True),
        sa.Column("finish", sa.String(length=32), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("drawer", sa.String(length=32), nullable=True),
        sa.Column("slot", sa.String(length=32), nullable=True),
        sa.Column("is_pending", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=8), nullable=True),
        sa.Column("is_proxy", sa.Boolean(), nullable=False),
        sa.Column("from_drawer", sa.String(length=32), nullable=True),
        sa.Column("from_slot", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_rows", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inventory_rows_card_id"), ["card_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_rows_drawer"), ["drawer"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_rows_finish"), ["finish"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventory_rows_is_pending"), ["is_pending"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_inventory_rows_is_proxy"), ["is_proxy"], unique=False)
        batch_op.create_index(batch_op.f("ix_inventory_rows_language"), ["language"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventory_rows_storage_location_id"),
            ["storage_location_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_inventory_rows_user_id"), ["user_id"], unique=False)

    op.create_table(
        "playgroup_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playgroup_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playgroup_id"],
            ["playgroups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("playgroup_id", "user_id", name="uq_playgroup_members_pg_user"),
    )
    with op.batch_alter_table("playgroup_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_playgroup_members_playgroup_id"), ["playgroup_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_playgroup_members_user_id"), ["user_id"], unique=False)

    op.create_table(
        "shares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("showcase_id", sa.Integer(), nullable=False),
        sa.Column("playgroup_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playgroup_id"],
            ["playgroups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["showcase_id"],
            ["showcases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("showcase_id", "playgroup_id", name="uq_shares_showcase_playgroup"),
    )
    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shares_playgroup_id"), ["playgroup_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_shares_showcase_id"), ["showcase_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_shares_user_id"), ["user_id"], unique=False)

    op.create_table(
        "token_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type_line", sa.String(length=255), nullable=True),
        sa.Column("subtype", sa.String(length=64), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("set_code", sa.String(length=32), nullable=True),
        sa.Column("collector_number", sa.String(length=32), nullable=True),
        sa.Column("scryfall_id", sa.String(length=64), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("is_double_sided", sa.Boolean(), nullable=False),
        sa.Column("back_name", sa.String(length=255), nullable=True),
        sa.Column("back_image_url", sa.Text(), nullable=True),
        sa.Column("back_set_code", sa.String(length=32), nullable=True),
        sa.Column("back_collector_number", sa.String(length=32), nullable=True),
        sa.Column("storage_location_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["storage_location_id"], ["storage_locations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("token_inventory", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_token_inventory_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_token_inventory_storage_location_id"),
            ["storage_location_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_token_inventory_user_id"), ["user_id"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposer_user_id", sa.Integer(), nullable=True),
        sa.Column("recipient_user_id", sa.Integer(), nullable=True),
        sa.Column("playgroup_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("proposer_note", sa.Text(), nullable=True),
        sa.Column("recipient_note", sa.Text(), nullable=True),
        sa.Column("proposer_name_at_trade", sa.Text(), nullable=True),
        sa.Column("recipient_name_at_trade", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["playgroup_id"],
            ["playgroups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposer_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trades_playgroup_id"), ["playgroup_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_trades_proposer_user_id"), ["proposer_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_trades_recipient_user_id"), ["recipient_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trades_status"), ["status"], unique=False)

    op.create_table(
        "transaction_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("finish", sa.String(length=32), nullable=True),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("source_location", sa.String(length=255), nullable=True),
        sa.Column("destination_location", sa.String(length=255), nullable=True),
        sa.Column("batch_id", sa.Integer(), nullable=True),
        sa.Column("inventory_row_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["import_batches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transaction_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_transaction_logs_batch_id"), ["batch_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transaction_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transaction_logs_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_transaction_logs_inventory_row_id"), ["inventory_row_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_transaction_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "deck_bracket_estimates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.Column("estimated_bracket", sa.Integer(), nullable=False),
        sa.Column("mechanics_bracket", sa.Integer(), nullable=False),
        sa.Column("intent_bracket", sa.Integer(), nullable=True),
        sa.Column("final_bracket", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "generated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("rules_version", sa.String(length=32), nullable=False),
        sa.Column("confidence_tagging_coverage", sa.Float(), nullable=True),
        sa.Column("confidence_mechanics_clarity", sa.Float(), nullable=True),
        sa.Column("confidence_intent_alignment", sa.Float(), nullable=True),
        sa.Column("confidence_combo_detection_depth", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("deck_bracket_estimates", schema=None) as batch_op:
        batch_op.create_index("ix_bracket_estimates_deck", ["deck_id"], unique=False)

    op.create_table(
        "deck_token_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.Column("token_inventory_id", sa.Integer(), nullable=True),
        sa.Column("token_name", sa.String(length=255), nullable=False),
        sa.Column("quantity_needed", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["token_inventory_id"], ["token_inventory.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deck_token_requirements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deck_token_requirements_deck_id"), ["deck_id"], unique=False
        )

    op.create_table(
        "game_seats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("seat_number", sa.Integer(), nullable=False),
        sa.Column("player_name", sa.String(length=128), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=True),
        sa.Column("placement", sa.Integer(), nullable=True),
        sa.Column("starting_life", sa.Integer(), nullable=False),
        sa.Column("final_life", sa.Integer(), nullable=True),
        sa.Column("grid_position", sa.String(length=4), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("user_name_at_game", sa.Text(), nullable=True),
        sa.Column("deck_name_at_game", sa.Text(), nullable=True),
        sa.Column("commander_name_at_game", sa.Text(), nullable=True),
        sa.Column(
            "art_background_hidden", sa.Boolean(), server_default=sa.false(), nullable=False
        ),  # FIXUP #1
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("game_seats", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_game_seats_game_id"), ["game_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_game_seats_user_id"), ["user_id"], unique=False)

    op.create_table(
        "showcase_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("showcase_id", sa.Integer(), nullable=False),
        sa.Column("inventory_row_id", sa.Integer(), nullable=False),
        sa.Column("quantity_offered", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["inventory_row_id"], ["inventory_rows.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["showcase_id"],
            ["showcases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "showcase_id", "inventory_row_id", name="uq_showcase_items_showcase_inv"
        ),
    )
    with op.batch_alter_table("showcase_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_showcase_items_inventory_row_id"), ["inventory_row_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_showcase_items_showcase_id"), ["showcase_id"], unique=False
        )

    op.create_table(
        "deck_bracket_findings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.Column("estimate_id", sa.Integer(), nullable=False),
        sa.Column("finding_type", sa.String(length=64), nullable=False),
        sa.Column("finding_value", sa.String(length=255), nullable=True),
        sa.Column(
            "severity", sa.String(length=16), server_default=sa.text("'info'"), nullable=False
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("contributes_to_bracket", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), server_default=sa.text("(1.0)"), nullable=False),
        sa.ForeignKeyConstraint(["deck_id"], ["decks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["estimate_id"], ["deck_bracket_estimates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sqlite_autoincrement=True,
    )
    with op.batch_alter_table("deck_bracket_findings", schema=None) as batch_op:
        batch_op.create_index("ix_bracket_findings_estimate", ["estimate_id"], unique=False)

    op.create_table(
        "trade_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("inventory_row_id", sa.Integer(), nullable=True),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("showcase_item_id", sa.Integer(), nullable=True),
        sa.Column("finish", sa.String(length=32), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("card_name_at_trade", sa.Text(), nullable=True),
        sa.Column("card_set_code_at_trade", sa.String(length=32), nullable=True),
        sa.Column("card_collector_number_at_trade", sa.String(length=32), nullable=True),
        sa.Column("finish_at_trade", sa.String(length=32), nullable=True),
        sa.Column("quantity_at_trade", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
        ),
        sa.ForeignKeyConstraint(["inventory_row_id"], ["inventory_rows.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["showcase_item_id"], ["showcase_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trade_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trade_items_card_id"), ["card_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_trade_items_inventory_row_id"), ["inventory_row_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trade_items_side"), ["side"], unique=False)
        batch_op.create_index(batch_op.f("ix_trade_items_trade_id"), ["trade_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trade_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trade_items_trade_id"))
        batch_op.drop_index(batch_op.f("ix_trade_items_side"))
        batch_op.drop_index(batch_op.f("ix_trade_items_inventory_row_id"))
        batch_op.drop_index(batch_op.f("ix_trade_items_card_id"))

    op.drop_table("trade_items")
    with op.batch_alter_table("deck_bracket_findings", schema=None) as batch_op:
        batch_op.drop_index("ix_bracket_findings_estimate")

    op.drop_table("deck_bracket_findings")
    with op.batch_alter_table("showcase_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_showcase_items_showcase_id"))
        batch_op.drop_index(batch_op.f("ix_showcase_items_inventory_row_id"))

    op.drop_table("showcase_items")
    with op.batch_alter_table("game_seats", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_game_seats_user_id"))
        batch_op.drop_index(batch_op.f("ix_game_seats_game_id"))

    op.drop_table("game_seats")
    with op.batch_alter_table("deck_token_requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deck_token_requirements_deck_id"))

    op.drop_table("deck_token_requirements")
    with op.batch_alter_table("deck_bracket_estimates", schema=None) as batch_op:
        batch_op.drop_index("ix_bracket_estimates_deck")

    op.drop_table("deck_bracket_estimates")
    with op.batch_alter_table("transaction_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transaction_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_transaction_logs_inventory_row_id"))
        batch_op.drop_index(batch_op.f("ix_transaction_logs_event_type"))
        batch_op.drop_index(batch_op.f("ix_transaction_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_transaction_logs_batch_id"))

    op.drop_table("transaction_logs")
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_status"))
        batch_op.drop_index(batch_op.f("ix_trades_recipient_user_id"))
        batch_op.drop_index(batch_op.f("ix_trades_proposer_user_id"))
        batch_op.drop_index(batch_op.f("ix_trades_playgroup_id"))

    op.drop_table("trades")
    with op.batch_alter_table("token_inventory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_inventory_user_id"))
        batch_op.drop_index(batch_op.f("ix_token_inventory_storage_location_id"))
        batch_op.drop_index(batch_op.f("ix_token_inventory_name"))

    op.drop_table("token_inventory")
    with op.batch_alter_table("shares", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shares_user_id"))
        batch_op.drop_index(batch_op.f("ix_shares_showcase_id"))
        batch_op.drop_index(batch_op.f("ix_shares_playgroup_id"))

    op.drop_table("shares")
    with op.batch_alter_table("playgroup_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_playgroup_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_playgroup_members_playgroup_id"))

    op.drop_table("playgroup_members")
    with op.batch_alter_table("inventory_rows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_rows_user_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_rows_storage_location_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_rows_language"))
        batch_op.drop_index(batch_op.f("ix_inventory_rows_is_proxy"))
        batch_op.drop_index(batch_op.f("ix_inventory_rows_is_pending"))
        batch_op.drop_index(batch_op.f("ix_inventory_rows_finish"))
        batch_op.drop_index(batch_op.f("ix_inventory_rows_drawer"))
        batch_op.drop_index(batch_op.f("ix_inventory_rows_card_id"))

    op.drop_table("inventory_rows")
    with op.batch_alter_table("games", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_games_user_id"))
        batch_op.drop_index(batch_op.f("ix_games_playgroup_id"))

    op.drop_table("games")
    with op.batch_alter_table("decks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decks_variant_group_id"))
        batch_op.drop_index(batch_op.f("ix_decks_user_id"))
        batch_op.drop_index(batch_op.f("ix_decks_storage_location_id"))
        batch_op.drop_index(batch_op.f("ix_decks_name"))

    op.drop_table("decks")
    with op.batch_alter_table("watchlist", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_watchlist_user_card_name",
            sqlite_where=sa.text("card_name IS NOT NULL"),
            postgresql_where=sa.text("card_name IS NOT NULL"),
        )
        batch_op.drop_index(
            "uq_watchlist_user_card_id",
            sqlite_where=sa.text("card_id IS NOT NULL"),
            postgresql_where=sa.text("card_id IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_watchlist_user_id"))

    op.drop_table("watchlist")
    with op.batch_alter_table("variant_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_variant_groups_user_id"))
        batch_op.drop_index(batch_op.f("ix_variant_groups_name"))

    op.drop_table("variant_groups")
    with op.batch_alter_table("storage_locations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storage_locations_user_id"))
        batch_op.drop_index(batch_op.f("ix_storage_locations_type"))
        batch_op.drop_index(batch_op.f("ix_storage_locations_parent_id"))
        batch_op.drop_index(batch_op.f("ix_storage_locations_name"))
        batch_op.drop_index(batch_op.f("ix_storage_locations_mode"))

    op.drop_table("storage_locations")
    with op.batch_alter_table("showcases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_showcases_user_id"))

    op.drop_table("showcases")
    with op.batch_alter_table("playgroups", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_playgroups_join_code",
            sqlite_where=sa.text("join_code IS NOT NULL"),
            postgresql_where=sa.text("join_code IS NOT NULL"),
        )
        batch_op.drop_index(batch_op.f("ix_playgroups_name"))
        batch_op.drop_index(batch_op.f("ix_playgroups_created_by"))

    op.drop_table("playgroups")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_user_id"))

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_batches_user_id"))

    op.drop_table("import_batches")
    with op.batch_alter_table("game_changer_cards", schema=None) as batch_op:
        batch_op.drop_index("ix_game_changer_active")

    op.drop_table("game_changer_cards")
    with op.batch_alter_table("card_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_card_tags_tag")
        batch_op.drop_index("ix_card_tags_card")

    op.drop_table("card_tags")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("scryfall_cards", schema=None) as batch_op:
        batch_op.drop_index("ix_scryfall_cards_set_collector")
        batch_op.drop_index("ix_scryfall_cards_name")

    op.drop_table("scryfall_cards")
    op.drop_table("scryfall_bulk_meta")
    op.drop_table("commander_bracket_rules")
    with op.batch_alter_table("cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cards_set_code"))
        batch_op.drop_index(batch_op.f("ix_cards_scryfall_id"))
        batch_op.drop_index(batch_op.f("ix_cards_name"))
        batch_op.drop_index(batch_op.f("ix_cards_collector_number"))

    op.drop_table("cards")
    # ### end Alembic commands ###
